### ISSUE TITLE
Add tag for 1.0 release

### ISSUE THREAD

**Issue by unho** [ubernostrum/django-contact-form#16]
https://github.com/ubernostrum/django-contact-form/commit/6d66d3a0e445204c847c31a7f4b6cc934d949abf is not a proper way to add a tag.

**Comment by ubernostrum** [comment]
That's an imported hg tag commit. I'll get it fixed.

**Comment by ubernostrum** [comment]
Tagged 7e8bc22352edd4a2a82b5b6ed65b25bf2b608f3e as 1.0 since that's when the version bump in `setup.py` happened.
