### ISSUE TITLE
How about an option to configure the email that will receive the messages?

### ISSUE THREAD

**Issue by carlosribas** [ubernostrum/django-contact-form#20]
In my case, I do not want the same person getting error messages and contact form messages. So, in my settings file, I set up a "CONTACT_EMAIL" tuple, then I changed this line in forms.py:

`recipient_list = [mail_tuple[1] for mail_tuple in settings.MANAGERS]`

to

`recipient_list = [mail_tuple[1] for mail_tuple in settings.CONTACT_EMAIL]`

**Comment by ubernostrum** [comment]
There is a way to configure it -- subclass and do exactly what you did, then use your subclass :)
