### ISSUE TITLE
Django 1.11b1 context must be a dict rather than RequestContext

### ISSUE THREAD

**Issue by marc-gist** [ubernostrum/django-contact-form#23]
Context must be a dict rather than RequestContext.
Request Method:	POST
Request URL:	http://xxx.ca:8000/contact/
Django Version:	1.11b1
Exception Type:	TypeError
Exception Value:	
context must be a dict rather than RequestContext.
Exception Location:	/home/xxx/py3env/lib/python3.5/site-packages/django/template/context.py in make_context, line 285
Python Executable:	/home/xxx/py3env/bin/python
Python Version:	3.5.2

any ideas?

**Comment by ubernostrum** [comment]
I'm not sure about this, but I'm also not yet testing against Django 1.11. I'd need to see more code -- in particular any custom stuff you're doing -- to know whether there's a bug in django-contact-form here.

**Comment by dwaynebailey** [comment]
@ubernostrum @marc-gist the fix is almost certainly https://github.com/ubernostrum/django-contact-form/pull/22

**Comment by marc-gist** [comment]
thank you @dwaynebailey and thank you @ubernostrum for sharing your work. it was instrumental in the creation of my own custom module i ended up making.
