### ISSUE TITLE
Test against Django 1.11b1

### ISSUE THREAD

**Issue by dwaynebailey** [ubernostrum/django-contact-form#26]
contact-form should test against Django 1.11b1.  I didn't look deeply but you can't easily specify 1.11b1 in the Makefile based system:

1.11b1 tries to instal 1.11b1.0
1.11 tries to install 1.11.0

Both fail

**Comment by timgraham** [comment]
Testing is added in https://github.com/ubernostrum/django-contact-form/pull/33.
