### ISSUE TITLE
Cut a release that supports Django 1.11?

### ISSUE THREAD

**Issue by wylee** [ubernostrum/django-contact-form#29]
I'm starting to upgrade a project from Django 1.10 to 1.11 and the only blocker so far is django-contact-form. I cloned the django-contact-form repo and tested it against Django 1.11 and all tests pass. Would it be possible to cut a release that supports Django 1.11?

**Comment by ubernostrum** [comment]
It's in progress. Should have releases out of all my stuff within the next week or two.

**Comment by ubernostrum** [comment]
1.4 is out supporting Django 1.11.
