### ISSUE TITLE
Possible bug in forms.py

### ISSUE THREAD

**Issue by cpattersonit** [ubernostrum/django-contact-form#34]
Hello,

I am using this package for the first time, the latest stable release (1.4.1) in a Django 1.9.13 project with Python 2.7.13.  The first thing I did was try to use the package out of the box without any subclassing.  However, I ran into an error that is traced back to the forms module trying to import Site from the Django sites framework:

    from django.contrib.sites.models import Site

I do not have the sites framework installed in this project.  The app is supposed to fallback to a RequestSite instance if the sites framework is not installed, but I am getting the following error:

RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

As a test, I commented out the import line above as well as the check for the sites framework in the get_context method:

        if Site._meta.installed:
            site = Site.objects.get_current()
        else:
            site = RequestSite(self.request)

I replaced that part with the following simple line that assumes sites is not installed:

    site = RequestSite(self.request)

This caused the app to work correctly.  I will attempt to install the sites framework in my project to get this app working, but I just wanted to let you know about this issue in case you wanted to fix it to comply with the intent written in the documentation.  Please let me know if I am incorrect.

Thanks,
Christopher Patterson
cpattersonit@gmail.com

**Comment by ubernostrum** [comment]
Django now has a helper for this, but looks like it was never updated to use it. I'll get it fixed in the next day or two.

**Comment by ubernostrum** [comment]
Just released 1.4.2 with the fix for this.

**Comment by cpattersonit** [comment]
Thank you!
