### ISSUE TITLE
Implementation Issues

### ISSUE THREAD

**Issue by stromal** [ubernostrum/django-contact-form#54]
I have installed the program fine.
I have trouble reading the [quick start guide](https://django-contact-form.readthedocs.io/en/1.8.1/quickstart.html#url-configuration).

1. I have added the `'contact_form'` to your `setting.py/INSTALLED_APPS`
2. `contact_form.urls` is a from but I have no idea how to use it or from where to get it.
3. Is this `contact_form.urls` goes in to the main application folder where the setting.py is?
4. "You can include it wherever you like in your site’s URL configuration; for example, to have it live at the URL /contact/:" what is this URL is a new application and contact is a subfolder?
5. "If you’ll be using a custom form class, you’ll need to manually set up your URLs so you can tell django-contact-form about your form class. For example" in what cases do I need this and 
6. I just want to set it up for 1 template on the main landing page, How can I do that?

Thank you.

**Comment by ubernostrum** [comment]
These mostly are general questions about how Django itself works, rather than bugs or problems in django-contact-form. Please use a general Django help/support forum rather than filing this as a bug here.
