### ISSUE TITLE
NoReverseMatch

### ISSUE THREAD

**Issue by tingletech** [ubernostrum/django-contact-form#6]
I'm trying to follow the tutorial at http://atsoftware.de/2015/02/django-contact-form-full-tutorial-custom-example-in-django-1-7/ ; but I keep getting a `NoReverseMatch` error.  Any ideas what I'm doing wrong?

here is the error I'm getting: https://gist.github.com/tingletech/1f90d27c674ed978672e#file-error-txt

I added this to `urls.py` https://gist.github.com/tingletech/1f90d27c674ed978672e#file-urls-py-diff

And this is my `templates/contact_form`:

`contact_form.html`
```html
{% extends 'calisphere/base.html' %}

{% block content %}
                        <form method="post">{% csrf_token %}
                            {% for field in form %}
                                <div class="fieldWrapper">
                                    {{ field.errors }}
                                    {{ field.label_tag }} {{ field }}
                                </div>
                            {% endfor %}
                            <input type="submit" value="Submit">
                        </form>
{% endblock %}
```
`contact_form.txt`
```
From: {{ name }} {{ email }}
Message: {{ reason }}
{{ body }}
```

`contact_form_sent.html`
```
<p>Message sent!</p>
```

`contact_form_subject.txt`
```
Contact form message
```

<img width="674" alt="screen shot 2015-08-26 at 9 45 23 pm" src="https://cloud.githubusercontent.com/assets/227374/9512768/d7abd89e-4c3b-11e5-850a-e702314799af.png">

<img width="462" alt="screen shot 2015-08-26 at 9 46 31 pm" src="https://cloud.githubusercontent.com/assets/227374/9512780/080d7448-4c3c-11e5-8f71-d7f58c214016.png">

<img width="824" alt="screen shot 2015-08-26 at 9 46 42 pm" src="https://cloud.githubusercontent.com/assets/227374/9512779/07f157cc-4c3c-11e5-9bbf-09a543dbc5cc.png">

```
pip freeze | grep django-contact
django-contact-form==1.1
```

**Comment by ubernostrum** [comment]
Something must be wrong in your URL configuration, but I can't tell what it is. The giveaway seems to be this in the traceback: "0 pattern(s) tried: []".

**Comment by tingletech** [comment]
Humm, I included my `urls.py` in the gist

```diff
diff --git a/calisphere/urls.py b/calisphere/urls.py
index aa6b6cc..a438177 100644
--- a/calisphere/urls.py
+++ b/calisphere/urls.py
@@ -31,4 +31,5 @@ urlpatterns = patterns('calisphere',
     url(r'^relatedCollections/', 'views.relatedCollections', name='relatedCollections'),
     url(r'^carousel/', 'views.itemViewCarousel', name='carousel'),
     url(r'^contactOwner/', 'views.contactOwner', name='contactOwner'),
+    url(r'^CONTACT/', include('contact_form.urls')),
 )
```

**Comment by tingletech** [comment]
I put it in the other `urls.py` file and it worked.
