### ISSUE TITLE
de translation django.mo not up 2 date?

### ISSUE THREAD

**Issue by frlan** [ubernostrum/django-contact-form#65]
I'm debugging a funny issue where in German localization "deine Emailadresse" is printed, whereas the string is translated in django.po with "Deine E-Mail-Adresse" (which looks much better to me). The first version I can only find in the django.mo.

**Comment by ubernostrum** [comment]
It's entirely possible that it's not up to date -- I don't generally touch the translation files, and rely on contributors to get them right.

**Comment by frlan** [comment]
I can see, that .mo files are checked in even though they are in .gitignore listed. However, running compile messages seemed to fixed the issue for me in a local checkout. Now I'm a little unsure, how to provide it upstream so it can be fixed on all installation -- conflict checked in mo and .gitignore.

**Comment by ubernostrum** [comment]
I don't know what the current best practices are around shipping compiled translation files, so I'm also not sure what the best way forward is.

**Comment by frlan** [comment]
Hmm. I guess I will provide a MR with upgrade mo-files than and let's see ;)
